INSERT INTO TB_PRODUCT (PRODUCT_ID, NAME, DESCRIPTION, PRICE) values(1, 'teste1', 'teste1', 100)
INSERT INTO TB_PRODUCT (PRODUCT_ID, NAME, DESCRIPTION, PRICE) values(2, 'teste2', 'teste2', 200)
INSERT INTO TB_PRODUCT (PRODUCT_ID, NAME, DESCRIPTION, PRICE) values(3, 'teste3', 'teste3', 300)